spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/cryptoalert
        username:
        password:
        initialization-mode: always
    tomcat:
        remoteip:
            remote-ip-header: x-forwarded-for
            protocol-header: x-forwarded-proto

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                jdbc:
                    batch_size: 16
                order_inserts: true
                generate_statistics: true

    mail:
        host: localhost
        port: 1025
        username: hello
        password: hello

        properties:
            mail:
                smtp:
                    ssl:
                        trust: "*"
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000